#!/usr/bin/python3
import os
import py_compile

pyfile = os.environ.get('PYFILE')
if not pyfile:
    print("Error: PYFILE environment variable not set")
    exit(1)

print("Compiling {} ...".format(pyfile))
py_compile.compile(pyfile, cfile=pyfile + 'c')
